src/kb_app/urls.py
from django.urls import path

from . import views

app_name = "keyboards"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("catalog/", views.KeyBoardList.as_view(), name="keyboard_list"),
    path(
        "catalog/<slug:keyboard_slug>/",
        views.KeyBoardDetails.as_view(),
        name="keyboard_details",
    ),
]

src/keyboard_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls  # type: ignore
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kb_app.urls", namespace="keyboards")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # type: ignore

urlpatterns.extend(debug_toolbar_urls())

src/kb_app/models.py
from django.db import models
from django.urls import reverse


class KeyBoard(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = (
            0,
            "Черновик",
        )
        PUBLISHED = (
            1,
            "Опубликовано",
        )

    name: models.CharField = models.CharField(
        max_length=100,
        verbose_name="Название клавиатуры",
    )
    slug: models.SlugField = models.SlugField(
        max_length=255,
        unique=True,
        db_index=True,
        verbose_name="Слаг",
    )
    photo: models.ImageField = models.ImageField(
        upload_to="photos/%Y/%m,%d/",
        verbose_name="Фото",
    )
    description: models.TextField = models.TextField(
        verbose_name="Описание",
    )
    is_published: models.BooleanField = models.BooleanField(
        choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
        default=Status.DRAFT,
        verbose_name="Статус",
    )
    price: models.IntegerField = models.IntegerField(
        default=0,
        verbose_name="Стоимость за единицу товара",
    )
    category: models.ForeignKey["Category"] = models.ForeignKey(
        "Category",
        on_delete=models.PROTECT,
        related_name="category",
        verbose_name="Категория",
    )
    counter: models.IntegerField = models.IntegerField(
        default=1,
        verbose_name="Количество единиц на складе",
    )
    specifications: models.OneToOneField["Specification"] = models.OneToOneField(
        "Specification",
        on_delete=models.CASCADE,
        related_name="specifications",
        verbose_name="Характеристики",
    )
    equipments: models.TextField = models.TextField(
        max_length=255,
        verbose_name="Комплектация",
    )
    created_at: models.DateTimeField = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )
    updated_at: models.DateTimeField = models.DateTimeField(
        auto_now=True,
        verbose_name="Дата редактирования",
    )

    class Meta:
        verbose_name = "Клавиатура"
        verbose_name_plural = "Клавиатуры"
        indexes = [models.Index(fields=["-created_at"])]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            "keyboards:keyboard_details", kwargs={"keyboard_slug": self.slug}
        )


class Category(models.Model):
    name: models.CharField = models.CharField(
        max_length=100,
        db_index=True,
        verbose_name="Название категории",
    )
    slug: models.SlugField = models.SlugField(
        max_length=255,
        unique=True,
        db_index=True,
        verbose_name="Слаг",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category", kwargs={"cat_slug": self.slug})


class Specification(models.Model):
    name: models.CharField = models.CharField(
        max_length=50,
        default=None,
        verbose_name="Название клавиатуры",
    )
    key_material: models.CharField = models.CharField(
        max_length=50,
        verbose_name="Материал клавиш",
    )
    size: models.IntegerField = models.IntegerField(
        verbose_name="Размер клавиатуры",
    )
    number_of_keys: models.IntegerField = models.IntegerField(
        verbose_name="Количество клавиш",
    )
    os_compatibility: models.CharField = models.CharField(
        max_length=255,
        verbose_name="Совместимость ОС",
    )
    backlight: models.CharField = models.CharField(
        max_length=50,
        verbose_name="Подсветка",
    )
    connection_interface: models.CharField = models.CharField(
        max_length=255,
        verbose_name="Интерфейс подключения",
    )
    weight: models.FloatField = models.FloatField(
        verbose_name="Вес",
    )
    country_of_manufacture: models.CharField = models.CharField(
        max_length=255,
        verbose_name="Страна производитель",
    )
    brand: models.CharField = models.CharField(
        max_length=255,
        verbose_name="Бренд",
    )

    class Meta:
        verbose_name = "Характеристика"
        verbose_name_plural = "Характеристики"

    def __str__(self):
        return f"{self.brand}, {self.size}% - {self.number_of_keys} клавиш, {self.key_material}, {self.connection_interface}"

src/kb_app/views.py
from django.views.generic import DetailView, ListView, TemplateView

from .models import KeyBoard


class Home(TemplateView):
    template_name = "kb_app/home.html"
    extra_content = {
        "title": "Главная страница",
    }


class KeyBoardList(ListView):
    model = KeyBoard
    template_name = "kb_app/keyboard_list.html"
    context_object_name = "kb_list"
    extra_context = {
        "title": "Каталог",
    }


class KeyBoardDetails(DetailView):
    model = KeyBoard
    template_name = "kb_app/keyboard_details.html"
    slug_url_kwarg = "keyboard_slug"
    context_object_name = "keyboard"

src/kb_app/templates/kb_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col">
      Преймущество 1
    </div>
    <div class="col">
      Преймущество 2
    </div>
    <div class="col">
      Преймущество 3
    </div>
  </div>
</div>
{% endblock %}

src/kb_app/templates/kb_app/keyboard_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <h1>{{keyboard.name}}</h1>
  <img src="{{keyboard.photo.url}}">
  <p>{{keyboard.description}}</p>
  <p>{{keyboard.counter}}</p>
  <p>{{keyboard.specifications}}</p>
  <p>{{keyboard.equipments}}</p>
</div>
{% endblock %}

src/kb_app/templates/kb_app/keyboard_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1 class="text-center">Механические клавиатуры</h1>
    {% if kb_list %}
    {% for keyboard in kb_list %}
    <div class="card" style="width: 18rem;">
        <img src={{keyboard.photo.url}} class="card-img-top" alt="keyboard photo">
        <div class="card-body">
            <h5 class="card-title">{{keyboard.name}}</h5>
            <p class="card-text">{{keyboard.description}}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">{{keyboard.price}} ₽</li>
        </ul>
        <a href="{{keyboard.get_absolute_url}}" class="btn btn-primary">Go somewhere</a>
    </div>
    {% endfor %}
    {% else %}
    <h2 class="text-muted text-center">Упс..Здесь пока ничего нет</h2>
    {% endif %}
</div>
{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body class="d-flex flex-column min-vh-100">
{% include 'include/nav.html' %}
{% block content %} {% endblock %}
{% include 'include/footer.html' %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

src/templates/include/footer.html
<nav class="navbar bg-body-tertiary mt-auto">
  <div class="container-fluid">
    <span class="navbar-text">
      Created by Nikita Y
    </span>
  </div>
</nav>

src/templates/include/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'keyboards:home' %}">KB</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'keyboards:keyboard_list' %}">Каталог клавиатур</a>
        </li>
      </ul>
    </div>
  </div>
</nav>